// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhFZCpNsxMlJxVZKMfVv4MCbgamb-vWA',
    appId: '1:150565376973:web:d3388a89ea6d4764a9ea84',
    messagingSenderId: '150565376973',
    projectId: 'todo-f4140',
    authDomain: 'todo-f4140.firebaseapp.com',
    databaseURL: 'https://todo-f4140-default-rtdb.firebaseio.com',
    storageBucket: 'todo-f4140.appspot.com',
    measurementId: 'G-ZJQD66NXMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8zPm0SIivmEqcFBp0C1uY9NJ4dO7iV6k',
    appId: '1:150565376973:android:57f7131c1ebf8fd4a9ea84',
    messagingSenderId: '150565376973',
    projectId: 'todo-f4140',
    databaseURL: 'https://todo-f4140-default-rtdb.firebaseio.com',
    storageBucket: 'todo-f4140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfbtJJxgsHY8H_vqtrgdEKzF_2XZKe2o',
    appId: '1:150565376973:ios:10a46857eb23b9ffa9ea84',
    messagingSenderId: '150565376973',
    projectId: 'todo-f4140',
    databaseURL: 'https://todo-f4140-default-rtdb.firebaseio.com',
    storageBucket: 'todo-f4140.appspot.com',
    androidClientId: '150565376973-eapo7gp38kvmhgpoiro8u4tdeck4fhkr.apps.googleusercontent.com',
    iosClientId: '150565376973-n2qmtedtoika4buuv81vbn9nu3mglnuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcfbtJJxgsHY8H_vqtrgdEKzF_2XZKe2o',
    appId: '1:150565376973:ios:10a46857eb23b9ffa9ea84',
    messagingSenderId: '150565376973',
    projectId: 'todo-f4140',
    databaseURL: 'https://todo-f4140-default-rtdb.firebaseio.com',
    storageBucket: 'todo-f4140.appspot.com',
    androidClientId: '150565376973-eapo7gp38kvmhgpoiro8u4tdeck4fhkr.apps.googleusercontent.com',
    iosClientId: '150565376973-n2qmtedtoika4buuv81vbn9nu3mglnuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenses',
  );
}
